//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDesk.BarcodeScannerService
{
    using Tecan.Sila2;
    
    
    ///  <summary>
    /// Data transfer object for the request of the Listen To Barcodes command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class ListenToBarcodesRequestDto : Tecan.Sila2.ISilaTransferObject, Tecan.Sila2.ISilaRequestObject
    {
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public ListenToBarcodesRequestDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        public ListenToBarcodesRequestDto(Tecan.Sila2.IBinaryStore store)
        {
        }
        
        ///  <summary>
        /// Gets the command identifier for this command
        /// </summary>
        /// <returns>The fully qualified command identifier</returns>
        public string CommandIdentifier
        {
            get
            {
                return "cocome.terminal/contracts/BarcodeScannerService/v1/Command/ListenToBarcodes";
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
    
    ///  <summary>
    /// Data transfer object for the intermediate response of the Listen To Barcodes command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class ListenToBarcodesIntermediateDto : Tecan.Sila2.ISilaTransferObject
    {
        
        private Tecan.Sila2.StringDto _intermediate;
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public ListenToBarcodesIntermediateDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        ///  <param name="intermediate"></param>
        public ListenToBarcodesIntermediateDto(string intermediate, Tecan.Sila2.IBinaryStore store)
        {
            Intermediate = new Tecan.Sila2.StringDto(intermediate, store);
        }
        
        ///  <summary>
        /// </summary>
        [ProtoBuf.ProtoMemberAttribute(1)]
        public Tecan.Sila2.StringDto Intermediate
        {
            get
            {
                return _intermediate;
            }
            set
            {
                _intermediate = value;
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
}
