//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDesk.PrintingService
{
    using Tecan.Sila2;
    
    
    ///  <summary>
    /// Data transfer object for the request of the Print Line command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class PrintLineRequestDto : Tecan.Sila2.ISilaTransferObject, Tecan.Sila2.ISilaRequestObject
    {
        
        private Tecan.Sila2.StringDto _line;
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public PrintLineRequestDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        ///  <param name="line"></param>
        public PrintLineRequestDto(string line, Tecan.Sila2.IBinaryStore store)
        {
            Line = new Tecan.Sila2.StringDto(line, store);
        }
        
        ///  <summary>
        /// </summary>
        [ProtoBuf.ProtoMemberAttribute(1)]
        public Tecan.Sila2.StringDto Line
        {
            get
            {
                return _line;
            }
            set
            {
                _line = value;
            }
        }
        
        ///  <summary>
        /// Gets the command identifier for this command
        /// </summary>
        /// <returns>The fully qualified command identifier</returns>
        public string CommandIdentifier
        {
            get
            {
                return "terminal/contracts/PrintingService/v1/Command/PrintLine";
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
    
    ///  <summary>
    /// Data transfer object for the request of the Start Next command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class StartNextRequestDto : Tecan.Sila2.ISilaTransferObject, Tecan.Sila2.ISilaRequestObject
    {
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public StartNextRequestDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        public StartNextRequestDto(Tecan.Sila2.IBinaryStore store)
        {
        }
        
        ///  <summary>
        /// Gets the command identifier for this command
        /// </summary>
        /// <returns>The fully qualified command identifier</returns>
        public string CommandIdentifier
        {
            get
            {
                return "terminal/contracts/PrintingService/v1/Command/StartNext";
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
}
