//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDesk.CashboxService
{
    using Tecan.Sila2;
    
    
    ///  <summary>
    /// Data transfer object for the request of the Listen To Cashdesk Buttons command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class ListenToCashdeskButtonsRequestDto : Tecan.Sila2.ISilaTransferObject, Tecan.Sila2.ISilaRequestObject
    {
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public ListenToCashdeskButtonsRequestDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        public ListenToCashdeskButtonsRequestDto(Tecan.Sila2.IBinaryStore store)
        {
        }
        
        ///  <summary>
        /// Gets the command identifier for this command
        /// </summary>
        /// <returns>The fully qualified command identifier</returns>
        public string CommandIdentifier
        {
            get
            {
                return "cocome.terminal/contracts/CashboxService/v1/Command/ListenToCashdeskButtons";
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
    
    ///  <summary>
    /// Data transfer object for the intermediate response of the Listen To Cashdesk Buttons command
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class ListenToCashdeskButtonsIntermediateDto : Tecan.Sila2.ISilaTransferObject
    {
        
        private CashboxButtonDto _intermediate;
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        public ListenToCashdeskButtonsIntermediateDto()
        {
        }
        
        ///  <summary>
        /// Create a new instance
        /// </summary>
        /// <param name="store">An object to organize binaries.</param>
        ///  <param name="intermediate"></param>
        public ListenToCashdeskButtonsIntermediateDto(CashboxButton intermediate, Tecan.Sila2.IBinaryStore store)
        {
            Intermediate = new CashboxButtonDto(intermediate, store);
        }
        
        ///  <summary>
        /// </summary>
        [ProtoBuf.ProtoMemberAttribute(1)]
        public CashboxButtonDto Intermediate
        {
            get
            {
                return _intermediate;
            }
            set
            {
                _intermediate = value;
            }
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
    
    ///  <summary>
    /// The data transfer object for the Cashbox Button enumeration
    /// </summary>
    [ProtoBuf.ProtoContractAttribute()]
    public class CashboxButtonDto : Tecan.Sila2.ISilaTransferObject<CashboxButton>
    {
        
        private Tecan.Sila2.StringDto _value;
        
        ///  <summary>
        /// Initializes a new instance (to be used by the serializer)
        /// </summary>
        public CashboxButtonDto()
        {
        }
        
        ///  <summary>
        /// Initializes a new data transfer object from the business object
        /// </summary>
        /// <param name="inner">The business object that should be transferred</param>
        /// <param name="store">A component to handle binary data</param>
        public CashboxButtonDto(CashboxButton inner, Tecan.Sila2.IBinaryStore store)
        {
            Value = inner.ToString();
        }
        
        ///  <summary>
        /// The string representation of the given enum member
        /// </summary>
        [ProtoBuf.ProtoMemberAttribute(1)]
        public Tecan.Sila2.StringDto Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
        
        ///  <summary>
        /// Extracts the transferred value
        /// </summary>
        /// <param name="store">The binary store in which to store binary data</param>
        /// <returns>the inner value</returns>
        public CashboxButton Extract(Tecan.Sila2.IBinaryStore store)
        {
            return ((CashboxButton)(System.Enum.Parse(typeof(CashboxButton), Value.Value)));
        }
        
        ///  <summary>
        /// Creates the data transfer object from the given object to transport
        /// </summary>
        /// <param name="inner">The object to transfer</param>
        /// <param name="store">An object to store binary data</param>
        public static CashboxButtonDto Create(CashboxButton inner, Tecan.Sila2.IBinaryStore store)
        {
            return new CashboxButtonDto(inner, store);
        }
        
        ///  <summary>
        /// Validates the contents of this transfer object
        /// </summary>
        /// <returns>A validation error or null, if no validation error occurred.</returns>
        public string GetValidationErrors()
        {
            return null;
        }
    }
}
