-- Dummy data
START TRANSACTION;

-- Enterprise values
INSERT INTO enterprises (name) VALUES ('CocomeSystem GmbH & Co. KG');

-- Store values
INSERT INTO stores (name, location, enterprise_id) VALUES ('Cocome WI', 'Wiesbaden', 1);
INSERT INTO stores (name, location, enterprise_id) VALUES ('Cocome F', 'Frankfurt', 1);
INSERT INTO stores (name, location, enterprise_id) VALUES ('Cocome MZ', 'Mainz', 1);

-- ProductSupplier values
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Schegel', 1);
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Kaufmann', 1);
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Lutz GmbH', 1);
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Scheffler GmbH', 1);
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Thiele', 1);
INSERT INTO product_suppliers (name, enterprise_id) VALUES ('Betz Lange', 1);

-- Product values
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000000, 23.15, 'Funny-frisch Chipsfrisch', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000001, 24.46, 'Knorr Suppenliebe', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000002, 24.3, 'Bio-Schweineschnitzel', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000003, 24.34, 'KÖLLN Müsli', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000004, 23.75, 'Jagdwurst', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000005, 28.79, 'ZOTT Monte Schoko', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000006, 24.37, 'Perwoll Waschmittel', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000007, 18.72, 'Weißer Rise', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000008, 5.62, 'Zott Sahnejoghurt', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000009, 8.38, 'Weizenbrot', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000010, 22.66, 'HENKELL Sekt', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000011, 28.63, 'Head & Shoulders Shampoo', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000012, 2.69, 'Endiviensalat', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000013, 9.74, 'Clementinen', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000014, 22.22, 'Hot Dog', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000015, 13.99, 'Blend-a-med Zahncreme', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000016, 16.4, 'Apfelsaft', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000017, 26.42, 'TEEKANNE Tee Waldbeere', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000018, 17.13, 'Wolfsbarsch', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000019, 10.83, 'Bio-Tafeläpfel', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000020, 20.5, 'Haribo Fruchtgummi', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000021, 2.37, 'Storck Knoppers', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000022, 8.97, 'Puten-Oberkeule', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000023, 28.4, 'HEISSE TASSE Instant-Suppe', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000024, 20.65, 'Coca Cola', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000025, 23.88, 'Martini', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000026, 6.34, 'VARTA Batterien', 1);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000027, 28.12, 'Weißer Rise', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000028, 19.37, 'KÖLLN Müsli', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000029, 8.67, 'Alpenhain Back-Käse', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000030, 23.8, 'Blend-a-med Zahncreme', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000031, 18.06, 'Storck Knoppers', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000032, 15.17, 'Toilettenpapier', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000033, 8.07, 'Perwoll Waschmittel', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000034, 5.35, 'Deutsche Kartoffeln', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000035, 18.48, 'Funny-frisch Chipsfrisch', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000036, 9.95, 'Rotkohl', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000037, 8.1, 'Head & Shoulders Shampoo', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000038, 29.28, 'VARTA Batterien', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000039, 3.88, 'Paprika', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000040, 27.83, 'Jagdwurst', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000041, 20.61, 'Dr. Oetker Ristorante Pizza', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000042, 26.14, 'Pringles', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000043, 27.9, 'Coca Cola', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000044, 29.62, 'Martini', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000045, 29.5, 'TEEKANNE Tee Waldbeere', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000046, 29.98, 'Clementinen', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000047, 20.92, 'Puten-Oberkeule', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000048, 13.59, 'Haribo Fruchtgummi', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000049, 26.91, 'Apfelsaft', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000050, 9.52, 'Endiviensalat', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000051, 12.65, 'Wolfsbarsch', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000052, 20.72, 'Knorr Suppenliebe', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000053, 7.81, 'Zott Sahnejoghurt', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000054, 6.41, 'Feldsalat', 2);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000055, 9.47, 'ZOTT Monte Schoko', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000056, 11.39, 'Rotkohl', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000057, 2.82, 'KÖLLN Müsli', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000058, 25.52, 'Weißer Rise', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000059, 24.28, 'Haribo Fruchtgummi', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000060, 18.24, 'Toilettenpapier', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000061, 5.78, 'Martini', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000062, 9.17, 'HEISSE TASSE Instant-Suppe', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000063, 4.43, 'Bio-Tafeläpfel', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000064, 8.91, 'Blend-a-med Zahncreme', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000065, 11.25, 'Endiviensalat', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000066, 12.54, 'Apfelsaft', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000067, 11.04, 'Jagdwurst', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000068, 27.03, 'Clementinen', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000069, 25.61, 'Bio-Schweineschnitzel', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000070, 17.66, 'Rinderhackfleisch', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000071, 19.57, 'Storck Knoppers', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000072, 11.05, 'SELTERS Mineralwasser', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000073, 28.85, 'Pringles', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000074, 15.28, 'Paprika', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000075, 7.31, 'VARTA Batterien', 3);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000076, 27.99, 'Hot Dog', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000077, 27.5, 'Bio-Schweineschnitzel', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000078, 12.41, 'Storck Knoppers', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000079, 15.48, 'Haribo Fruchtgummi', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000080, 8.0, 'Toilettenpapier', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000081, 19.54, 'Wolfsbarsch', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000082, 9.24, 'Zott Sahnejoghurt', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000083, 2.27, 'Apfelsaft', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000084, 8.07, 'Paprika', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000085, 16.07, 'Funny-frisch Chipsfrisch', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000086, 19.98, 'Weißer Rise', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000087, 4.41, 'Rinderhackfleisch', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000088, 28.71, 'ZOTT Monte Schoko', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000089, 8.63, 'Weizenbrot', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000090, 19.56, 'Endiviensalat', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000091, 12.64, 'Ferrero Nutella Schokocreme', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000092, 2.4, 'Milka Alpen Tafelschokolade', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000093, 22.35, 'Bio-Tafeläpfel', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000094, 17.8, 'Knorr Suppenliebe', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000095, 8.11, 'Blend-a-med Zahncreme', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000096, 9.34, 'Coca Cola', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000097, 23.24, 'Clementinen', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000098, 3.1, 'Head & Shoulders Shampoo', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000099, 16.68, 'HEISSE TASSE Instant-Suppe', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000100, 21.79, 'Alpenhain Back-Käse', 4);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000101, 20.21, 'Rotkohl', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000102, 17.85, 'Apfelsaft', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000103, 23.29, 'Martini', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000104, 20.42, 'Toilettenpapier', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000105, 5.07, 'TEEKANNE Tee Waldbeere', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000106, 24.21, 'Puten-Oberkeule', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000107, 22.84, 'Paprika', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000108, 20.24, 'Milka Alpen Tafelschokolade', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000109, 24.64, 'Bio-Schweineschnitzel', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000110, 11.05, 'Alpenhain Back-Käse', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000111, 5.7, 'Weizenbrot', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000112, 11.62, 'Haribo Fruchtgummi', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000113, 17.44, 'Perwoll Waschmittel', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000114, 22.43, 'HENKELL Sekt', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000115, 10.06, 'Head & Shoulders Shampoo', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000116, 16.57, 'Knorr Suppenliebe', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000117, 6.75, 'Weißer Rise', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000118, 4.92, 'Coca Cola', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000119, 22.1, 'Zott Sahnejoghurt', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000120, 2.84, 'ZOTT Monte Schoko', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000121, 20.32, 'Hot Dog', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000122, 18.43, 'VARTA Batterien', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000123, 23.25, 'Endiviensalat', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000124, 8.55, 'Ferrero Nutella Schokocreme', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000125, 18.0, 'Bio-Entrecôte', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000126, 18.45, 'Pringles', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000127, 6.98, 'Feldsalat', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000128, 6.15, 'KÖLLN Müsli', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000129, 27.66, 'Dr. Oetker Ristorante Pizza', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000130, 2.99, 'Storck Knoppers', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000131, 25.17, 'Funny-frisch Chipsfrisch', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000132, 13.42, 'Bio-Tafeläpfel', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000133, 22.71, 'Fleischwurst', 5);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000134, 10.48, 'Blend-a-med Zahncreme', 6);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000135, 16.46, 'Perwoll Waschmittel', 6);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000136, 7.1, 'KÖLLN Müsli', 6);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000137, 27.31, 'Rotkohl', 6);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000138, 18.25, 'Dr. Oetker Ristorante Pizza', 6);
INSERT INTO products (barcode, purchase_price, name, product_supplier_id) VALUES (10000139, 5.78, 'Milka Alpen Tafelschokolade', 6);

-- StockItem values
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (39.19, 33, 10, 50, 1, 77);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (15.47, 8, 10, 50, 1, 111);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (8.09, 6, 10, 50, 1, 140);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (41.47, 38, 10, 50, 1, 45);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (30.51, 21, 10, 50, 1, 101);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (32.61, 34, 10, 50, 1, 104);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (17.56, 30, 10, 50, 1, 67);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.32, 37, 10, 50, 1, 31);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (5.43, 34, 10, 50, 1, 40);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (12.14, 23, 10, 50, 1, 30);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.35, 14, 10, 50, 1, 96);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.85, 14, 10, 50, 1, 42);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (35.24, 34, 10, 50, 1, 132);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.34, 5, 10, 50, 1, 109);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.2, 29, 10, 50, 1, 81);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.2, 15, 10, 50, 1, 126);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (10.23, 4, 10, 50, 1, 76);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.4, 32, 10, 50, 1, 115);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.36, 15, 10, 50, 1, 93);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (39.06, 8, 10, 50, 1, 44);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.98, 12, 10, 50, 1, 108);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.89, 39, 10, 50, 1, 107);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (14.08, 10, 10, 50, 1, 116);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.25, 8, 10, 50, 1, 5);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (32.55, 23, 10, 50, 1, 124);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.29, 32, 10, 50, 1, 102);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (13.26, 36, 10, 50, 1, 56);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (41.3, 6, 10, 50, 1, 46);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (40.19, 19, 10, 50, 1, 89);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (35.85, 28, 10, 50, 1, 70);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (9.77, 31, 10, 50, 1, 128);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.34, 20, 10, 50, 1, 99);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (12.08, 18, 10, 50, 1, 90);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (17.71, 18, 10, 50, 1, 52);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (16.27, 8, 10, 50, 1, 113);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (24.92, 37, 10, 50, 1, 95);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.95, 14, 10, 50, 1, 58);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.19, 37, 10, 50, 1, 131);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (29.01, 2, 10, 50, 1, 53);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.45, 8, 10, 50, 1, 122);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (14.67, 13, 10, 50, 1, 135);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (24.42, 34, 10, 50, 1, 114);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (40.31, 15, 10, 50, 1, 6);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (22.5, 37, 10, 50, 1, 86);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.54, 13, 10, 50, 1, 61);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.29, 35, 10, 50, 1, 94);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (23.98, 29, 10, 50, 1, 19);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (23.35, 20, 10, 50, 1, 100);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.1, 4, 10, 50, 1, 106);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.49, 35, 10, 50, 1, 35);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (13.33, 16, 10, 50, 1, 51);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.34, 29, 10, 50, 1, 38);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (18.79, 5, 10, 50, 1, 133);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (12.56, 8, 10, 50, 1, 23);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (15.75, 19, 10, 50, 1, 66);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.77, 32, 10, 50, 1, 13);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (26.21, 26, 10, 50, 1, 8);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.3, 39, 10, 50, 1, 34);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (34.12, 20, 10, 50, 1, 7);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (23.2, 18, 10, 50, 1, 117);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (8.61, 37, 10, 50, 1, 129);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (19.59, 40, 10, 50, 1, 16);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (23.04, 29, 10, 50, 1, 136);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (10.93, 19, 10, 50, 2, 54);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (30.94, 29, 10, 50, 2, 120);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (16.27, 5, 10, 50, 2, 113);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.3, 28, 10, 50, 2, 34);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (8.09, 24, 10, 50, 2, 62);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.18, 30, 10, 50, 2, 84);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.73, 6, 10, 50, 2, 10);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.25, 28, 10, 50, 2, 5);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.83, 9, 10, 50, 2, 127);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.36, 35, 10, 50, 2, 93);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.32, 28, 10, 50, 2, 31);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.98, 7, 10, 50, 2, 112);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (21.24, 9, 10, 50, 2, 33);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (39.06, 7, 10, 50, 2, 44);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (14.08, 29, 10, 50, 2, 116);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (23.04, 33, 10, 50, 2, 136);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (26.21, 2, 10, 50, 2, 8);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (38.23, 1, 10, 50, 2, 138);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.87, 21, 10, 50, 2, 9);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (12.84, 35, 10, 50, 2, 63);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.1, 7, 10, 50, 2, 106);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (13.26, 2, 10, 50, 2, 56);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.77, 40, 10, 50, 2, 13);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (30.51, 31, 10, 50, 2, 101);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (41.97, 20, 10, 50, 2, 47);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (24.99, 23, 10, 50, 2, 103);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (8.88, 28, 10, 50, 2, 27);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.28, 33, 10, 50, 2, 32);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.34, 15, 10, 50, 2, 99);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (27.38, 29, 10, 50, 2, 91);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.72, 37, 10, 50, 2, 11);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (13.33, 29, 10, 50, 2, 51);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (14.67, 20, 10, 50, 2, 135);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (39.76, 37, 10, 50, 2, 24);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.91, 8, 10, 50, 2, 25);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.19, 14, 10, 50, 2, 131);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.8, 7, 10, 50, 2, 123);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.98, 2, 10, 50, 2, 121);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (40.31, 11, 10, 50, 2, 6);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.79, 14, 10, 50, 2, 134);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.3, 16, 10, 50, 2, 85);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (38.96, 17, 10, 50, 2, 41);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (15.47, 6, 10, 50, 2, 111);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.29, 14, 10, 50, 2, 102);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (40.39, 22, 10, 50, 2, 74);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.35, 16, 10, 50, 2, 96);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (41.3, 20, 10, 50, 3, 46);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (24.72, 22, 10, 50, 3, 71);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.99, 19, 10, 50, 3, 60);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (39.76, 40, 10, 50, 3, 24);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (29.01, 7, 10, 50, 3, 53);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (9.45, 4, 10, 50, 3, 118);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.97, 13, 10, 50, 3, 125);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (3.36, 14, 10, 50, 3, 93);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.34, 36, 10, 50, 3, 99);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.85, 20, 10, 50, 3, 42);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (35.24, 37, 10, 50, 3, 132);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.79, 27, 10, 50, 3, 134);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (34.08, 6, 10, 50, 3, 4);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (12.94, 28, 10, 50, 3, 83);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (8.09, 10, 10, 50, 3, 140);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (28.29, 4, 10, 50, 3, 102);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (32.61, 34, 10, 50, 3, 104);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (7.49, 26, 10, 50, 3, 35);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (36.6, 32, 10, 50, 3, 43);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (16.27, 10, 10, 50, 3, 113);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (27.12, 7, 10, 50, 3, 29);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (31.11, 25, 10, 50, 3, 15);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (34.12, 32, 10, 50, 3, 7);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (33.43, 34, 10, 50, 3, 26);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (11.2, 14, 10, 50, 3, 81);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (13.08, 26, 10, 50, 3, 97);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (24.92, 29, 10, 50, 3, 95);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (25.28, 31, 10, 50, 3, 32);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (19.03, 14, 10, 50, 3, 49);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (9.77, 2, 10, 50, 3, 128);
INSERT INTO stock_items (sales_price, amount, min_stock, max_stock, store_id, product_id) VALUES (4.19, 8, 10, 50, 3, 131);

-- ProductOrder values
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-17 10:16:53-00', '-infinity', 1);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-02 20:35:24-00', '2022-02-25 05:29:59-00', 1);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-16 10:47:30-00', '2022-02-27 15:53:33-00', 1);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-13 08:35:31-00', '2022-02-25 06:12:01-00', 2);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-17 06:24:29-00', '-infinity', 2);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-18 12:54:19-00', '-infinity', 2);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-19 17:10:12-00', '2022-02-27 16:16:32-00', 3);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-10 16:51:28-00', '-infinity', 3);
INSERT INTO product_orders (ordering_date, delivery_date, store_id) VALUES ('2022-02-05 19:58:42-00', '2022-02-14 01:49:59-00', 3);

-- OrderEntry values
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 60, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 68, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 70, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 56, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 59, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 74, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (13, 67, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 63, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 69, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 71, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 57, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 73, 1);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 77, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 90, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 78, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 79, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (12, 88, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 99, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 97, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 92, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 94, 2);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 138, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 137, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 136, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 139, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 140, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 135, 3);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 73, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 63, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 70, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (13, 71, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 56, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 76, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 69, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 61, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 66, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 65, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 60, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 58, 4);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 22, 5);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 1, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 10, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 15, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (13, 12, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 6, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 27, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 8, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 17, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 26, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (12, 18, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 2, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 16, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (13, 23, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 14, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 3, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 4, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 5, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 11, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (12, 21, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 7, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 25, 6);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 35, 7);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 43, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (5, 28, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 42, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 44, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 40, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 32, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (9, 38, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 46, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 35, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (12, 52, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 34, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 33, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 53, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 39, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 55, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 29, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 31, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (13, 41, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 37, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (7, 36, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 50, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (11, 48, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 54, 8);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 37, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 31, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (12, 35, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 28, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 36, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (14, 51, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (6, 44, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (10, 49, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (15, 30, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 47, 9);
INSERT INTO order_entries (amount, product_id, product_order_id) VALUES (8, 34, 9);

COMMIT;
