CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE enterprises (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    CONSTRAINT pk_enterprises PRIMARY KEY (id)
);

CREATE TABLE product_suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    enterprise_id bigint NULL,
    CONSTRAINT pk_product_suppliers PRIMARY KEY (id),
    CONSTRAINT fk_product_suppliers_enterprises_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES enterprises (id)
);

CREATE TABLE stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    location text NOT NULL,
    enterprise_id bigint NULL,
    CONSTRAINT pk_stores PRIMARY KEY (id),
    CONSTRAINT fk_stores_enterprises_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES enterprises (id)
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    barcode bigint NOT NULL,
    pruchase_price double precision NOT NULL,
    name text NOT NULL,
    product_supplier_id bigint NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_product_suppliers_product_supplier_id FOREIGN KEY (product_supplier_id) REFERENCES product_suppliers (id) ON DELETE CASCADE
);

CREATE TABLE product_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_date timestamp with time zone NOT NULL,
    ordering_date timestamp with time zone NOT NULL,
    store_id bigint NOT NULL,
    CONSTRAINT pk_product_orders PRIMARY KEY (id),
    CONSTRAINT fk_product_orders_stores_store_id FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE
);

CREATE TABLE stock_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sales_price double precision NOT NULL,
    amount integer NOT NULL,
    min_stock integer NOT NULL,
    max_stock integer NOT NULL,
    store_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT pk_stock_items PRIMARY KEY (id),
    CONSTRAINT fk_stock_items_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_items_stores_store_id FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE
);

CREATE TABLE order_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount integer NOT NULL,
    product_id bigint NOT NULL,
    product_order_id bigint NOT NULL,
    CONSTRAINT pk_order_entries PRIMARY KEY (id),
    CONSTRAINT fk_order_entries_product_orders_product_order_id FOREIGN KEY (product_order_id) REFERENCES product_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_entries_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX ix_order_entries_product_id ON order_entries (product_id);

CREATE INDEX ix_order_entries_product_order_id ON order_entries (product_order_id);

CREATE INDEX ix_product_orders_store_id ON product_orders (store_id);

CREATE INDEX ix_product_suppliers_enterprise_id ON product_suppliers (enterprise_id);

CREATE INDEX ix_products_product_supplier_id ON products (product_supplier_id);

CREATE INDEX ix_stock_items_product_id ON stock_items (product_id);

CREATE INDEX ix_stock_items_store_id ON stock_items (store_id);

CREATE INDEX ix_stores_enterprise_id ON stores (enterprise_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20220123102430_InitialCreate', '6.0.1');

COMMIT;

