version: '3'

services:

  postgres_db:
    
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      TZ: 'GMT+1'
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy123
      POSTGRES_DB: tradingsystem 
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/01_db_init.sql
      - ./db_content.sql:/docker-entrypoint-initdb.d/02_db_content.sql

  testing:
    
    image: 'postgres:latest'

    ports:
      - 5433:5432

    environment:
      TZ: 'GMT+1'
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy123
      POSTGRES_DB: tradingsystem 
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/01_db_init.sql
