//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashDesk
{
    
    
    ///  <summary>
    /// </summary>
    [Tecan.Sila2.SilaFeatureAttribute(true, "contracts")]
    [Tecan.Sila2.SilaIdentifierAttribute("DisplayController")]
    [Tecan.Sila2.SilaDisplayNameAttribute("Display Controller")]
    public partial interface IDisplayController
    {
        
        ///  <summary>
        /// </summary>
        /// <param name="displayText"></param>
        void SetDisplayText(string displayText);
    }
}
